import { readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = fileURLToPath(new URL("../", import.meta.url));
const entryPath = resolve(projectRoot, "js/app.js");
const bundlePath = resolve(projectRoot, "js/app.bundle.js");
const importsPattern = /import\s+\{[\s\S]*?\}\s+from\s+"([^"]+)";\n?/g;

async function collectModules(filePath, included = new Set()) {
  if (included.has(filePath)) {
    return "";
  }
  included.add(filePath);

  const source = await readFile(filePath, "utf8");
  const dependencies = [...source.matchAll(importsPattern)].map((match) =>
    resolve(dirname(filePath), match[1]),
  );

  let joinedDependencies = "";
  for (const dependency of dependencies) {
    joinedDependencies += await collectModules(dependency, included);
  }

  const browserSource = source
    .replace(importsPattern, "")
    .replace(/^export\s+/gm, "");
  const moduleName = relative(projectRoot, filePath);

  return `${joinedDependencies}\n// Source: ${moduleName}\n${browserSource}`;
}

export async function createOfflineBundle() {
  const source = await collectModules(entryPath);
  return `/* Generated by scripts/build-offline.mjs. Do not edit directly. */\n${source}`;
}

async function main() {
  const bundle = await createOfflineBundle();

  if (process.argv.includes("--check")) {
    const existing = await readFile(bundlePath, "utf8").catch(() => "");
    if (existing !== bundle) {
      throw new Error("Offline browser bundle is missing or out of date. Run the offline build.");
    }
    return;
  }

  await writeFile(bundlePath, bundle);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await main();
}
